### ISSUE TITLE
NameError: name 'train_valid_6k_image_name' is not defined

### ISSUE THREAD

**Issue by 363546178** [hustvl/VMA#1]
Hello! Thanks for sharing the great work! 
I use the python file : tools/custom/generate_line_final_from_origin.py like this:
`
python tools/custom/generate_line_final_from_origin.py ./data/sd_data/line/origin_data/line_data_6k.json ./data/sd_data/line/origin_data ./data/sd_data/line/cropped_data
`

it have some error:

`
process every 6k image to extract the 1k gt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.90it/s]
format dict: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 238312.73it/s]
Traceback (most recent call last):
  File "tools/custom/generate_line_final_from_origin.py", line 401, in <module>
    generate_line_final_from_original(args.all_gt_6k_json_file_path, args.data_root, args.out_dir, args.visualize)
  File "tools/custom/generate_line_final_from_origin.py", line 39, in generate_line_final_from_original
    json.dump(train_valid_6k_image_name, f)
NameError: name 'train_valid_6k_image_name' is not defined
`
The related code is as follows：

line38:    with open(os.path.join(out_dir, 'train_valid_6k_image_name.json'), 'w') as f:
line39:        json.dump(train_valid_6k_image_name, f)

the "train_valid_6k_image_name" is undefined

How can I modify the code here to solve this problem? Thank You!

**Comment by zyc10ud** [comment]
You can comment out lines 38 and 39 to resolve this problem, as these two lines of code and 'train_valid_6k_image_name.json' are useless.

**Comment by 363546178** [comment]
> You can comment out lines 38 and 39 to solve this problem, as these two lines of code and 'train_valid_6k_image_name.json' are useless.

I change the line 39 json.dump(train_valid_6k_image_name, f) to json.dump(valid_data_name_list, f), code can run normally
