### ISSUE TITLE
about how to transform PCL to BEV 3-channel RGB Image

### ISSUE THREAD

**Issue by MandyMo** [hustvl/VMA#11]
大兄弟，你知道怎么把一个PCL转换成三通道的RGB图像么，谢谢大兄弟。

**Comment by PeterJaq** [comment]
大兄弟有方案了么？

**Comment by MandyMo** [comment]
> 大兄弟有方案了么？

用cv2.applyColorMap之类的函数，然后输入是Intensity，输出是COLORMAP

**Comment by qpc001** [comment]
> > 大兄弟有方案了么？
> 
> 用cv2.applyColorMap之类的函数，然后输入是Intensity，输出是COLORMAP

bro, is there demo conver python code?
