### ISSUE TITLE
A little mistake of arguments mismatch

### ISSUE THREAD

**Issue by Coo1Sea** [hustvl/VMA#2]
Awesome work! 
I found a mistake the arguments in line 401 of tools/custom/generate_line_final_from_origin.py can't match the arguments in tools/custom/generate.sh. 
`generate_line_final_from_original(args.all_gt_6k_json_file_path, args.data_root, args.out_dir, args.visualize)`
`python generate_line_final_from_origin.py data/sd_data/line/origin_data data/sd_data/line/origin_data/line_data_6k.json data/sd_data/line/cropped_data --visualize`
It seems the arguments are in wrong order. It would return an error: IsADirectoryError: [Errno 21] Is a directory.

**Comment by Coo1Sea** [comment]
And another mistake is in line 296 of tools/custom/generate_line_final_from_origin.py,'bbox_minx' and 'bbox_maxx' aren't int will return an error: TypeError: slice indices must be integers or None or have an __index__ method.
I add 'int' to make sure they are integers and the code works:
`bbox_minx, bbox_miny, bbox_maxx, bbox_maxy = int(round(x) - 500), int(round(y) - 500), int(round(x) + 499), int(round(y) + 499)`

**Comment by zyc10ud** [comment]
Thank you for your attention to our work. The issue with the code has been resolved.
