### ISSUE TITLE
About images generation

### ISSUE THREAD

**Issue by kongdebug** [hustvl/VMA#4]
Thanks for your great work! 
I want to apply VMA to my own data and want to know how the images of `sd_data` are generated? I can only produce single-channel intensity images.

**Comment by zyc10ud** [comment]
I'm not quite sure how a single-channel intensity image is transformed into a three-channel RGB image, as this is a step in the production process of a BEV (Bird's Eye View) image. The data I have received is already in the form of a three-channel RGB image. Perhaps you can try using ```cv2.applyColorMap``` to apply a pseudocolor mapping to the intensity map to achieve this transformation.

**Comment by kongdebug** [comment]
Thank you very much for your reply.

**Comment by ycdhqzhiai** [comment]
Is this image generated by Maptr?

![Image](https://github.com/user-attachments/assets/f087432a-be38-4491-9328-7bfea2e78183)
but t maptr takes images as input, not point clouds
