### ISSUE TITLE
How to create sd dataset?

### ISSUE THREAD

**Issue by ker95qq** [hustvl/VMA#6]
Hello, 
sd dataset are making according to lidar pointscould. How to make it (x y z intensity) to given format image(r g b)?
It seems like hsv image, one change is  mapping from intensity, and another two channel is fixed？

**Comment by EchoQiHeng** [comment]
`            self.loss_single, all_cls_scores, all_pts_preds, all_attrs_preds, all_gt_labels_list, all_gt_attr_list, all_gt_shifts_pts_list) # 这里输入的是所有的pred_pts和gt_pts，但是是对每一个decoder layer来计算loss`
Chinese appeared in vmahead.py (Easter egg?

**Comment by Coo1Sea** [comment]
I want to know that too. I have tried many ways to replicate the image like the sd dataset but failed.

**Comment by PeterJaq** [comment]
> I want to know that too. I have tried many ways to replicate the image like the sd dataset but failed.

do you have any plan now?

**Comment by Coo1Sea** [comment]
> > I want to know that too. I have tried many ways to replicate the image like the sd dataset but failed.
> 
> do you have any plan now?

Sorry, no more plan. My group offers me some images like the sd dataset so that I don't need to think about it.
